[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = true

[tool.mypy]
disallow_untyped_calls = true
explicit_package_bases = true
ignore_missing_imports = true
install_types = true
exclude = '^(tests/)'