# --- Djangos Settings
debug: true
allowed_hosts:
  - "*"
django_secret: 'INSERT_SECRET'
# --- Tira specific settings
tira_root: /mnt/ceph/tira
# deployment = {disraptor, legacy}
deployment: legacy
logging_dir: /mnt/ceph/tira/log/tira-application
# in the legacy deployment, a path to the users file is needed
legacy_users_file: /mnt/ceph/tira/model/users/users.prototext
# grpc_host can be local or remote. If local, it will call localhost (i.e. for testing). If remote, it will call the vm-host
# When developing, set this option to local, otherwise you might accidentally remote-control the live-vms.
grpc_host: remote
host_grpc_port: 50051
application_grpc_port: 50052
