apiVersion: v1
kind: Service
metadata:
  name: tira-application-test
  namespace: services-tira
spec:
  type: NodePort
  selector:
    app: tira-application-test
  ports:
  - name: port-ui
    nodePort: 31580
    port: 80
    targetPort: 80
  - name: port-grpc-server
    nodePort: 31552
    port: 50052
    targetPort: 50052

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tira-application-test
  namespace: services-tira
spec:
  selector:
    matchLabels:
      app: tira-application-test
  replicas: 1
  template:
    metadata:
      labels:
        app: tira-application-test
      namespace: services-tira
    spec:
      containers:
      - name: tira-application-test
        image: registry.webis.de/code-lib/public-images/tira-application:0.0.7
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/mnt/ceph/tira"
          name: tira-cephfs
        - mountPath: "/tira/tira-application/src/config/settings.yml"
          name: config-yml
          subPath: settings-test.yml
        - mountPath: "/etc/discourse/client-api-key"
          name: tira-discourse-api-key
          subPath: key
        env:
          - name: DISRAPTOR_APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: disraptor-app-secret-key
                key: disraptor-app-secret-key
      volumes:
      - name: tira-cephfs
        hostPath:
          path: /mnt/ceph/tira
          type: Directory
      - name: tira-discourse-api-key
        secret:
          secretName: tira-discourse-api-key
      - name: config-yml
        configMap:
          name: tira-application-test-config

