apiVersion: v1
kind: Service
metadata:
  name: tira-web-client-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tira-web-client-2
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tira-web-client-2
spec:
  selector:
    matchLabels:
      app: tira-web-client-2
  replicas: 1
  template:
    metadata:
      labels:
        app: tira-web-client-2
    spec:
      containers:
      - name: tira-web-client-2
        image: webis/tira-web-2:0.0.4
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/mnt/ceph/tira"
          name: tira-cephfs
        - mountPath: "/tira/tira-application/src/config/settings-deploy.yml"
          name: config-yml
          subPath: settings-deploy.yml
        - mountPath: "/etc/discourse/client-api-key"
          name: tira-discourse-api-key
          subPath: key
      volumes:
      - name: tira-cephfs
        cephfs:
          monitors:
            - ceph.dw.webis.de
          path: /mnt/ceph/tira
          user: tira
          secretFile: "/etc/ceph/ceph.client.tira.secret"
          readOnly: false
      - name: tira-discourse-api-key
        secret:
          secretName: tira-discourse-api-key
      - name: config-yml
        configMap:
          name: tira-web2-config

